name: digital_sign
description: Digital Signature library with asymmetric private-public key cryptography. Hope for a plugin base.
version: 0.1.0
homepage: https://github.com/Terran-Source/dart-digital-sign
repository: https://github.com/Terran-Source/dart-digital-sign
issue_tracker: https://github.com/Terran-Source/dart-digital-sign/issues

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  # cryptography
  crypto: ^2.1.5
  convert: ^2.1.1
  # additional
  meta: ^1.2.2

dev_dependencies:
  test: ^1.15.3
